### ISSUE TITLE
Client host [97.90.35.107] blocked using zen.spamhaus.org

### ISSUE THREAD

**Issue by happysmash27** [root-io/vmail#92]
Can someone please unblock it from Vmail's side? I want to send email from my custom domain. Spamhaus.org does not seem very helpful for contacting for an unblock.

**Comment by root-io** [comment]
The issue is not related with us, the ip address (maybe even the entire ip block) was blocked by spamhaus. More info: https://www.spamhaus.org/query/ip/97.90.35.107
I recommend you get in touch with your hosting provider, most of the time it's another customer sending spam and using the same block ip as you.
Spamhaus won't be helpful because everything is done automatically, when the spam will stop, you'll be able to send your emails again from your server. Good luck ;)
